BANNER = """
 ██████╗ ██████╗ ███╗   ███╗██████╗ ██╗   ██╗████████╗███████╗██████╗ 
██╔════╝██╔═══██╗████╗ ████║██╔══██╗██║   ██║╚══██╔══╝██╔════╝██╔══██╗
██║     ██║   ██║██╔████╔██║██████╔╝██║   ██║   ██║   █████╗  ██████╔╝
██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║   ██║   ██║   ██╔══╝  ██╔══██╗
╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ╚██████╔╝   ██║   ███████╗██║  ██║
 ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝      ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝
"""  # Generated by: https://manytools.org/hacker-tools/ascii-banner/

# General
WAKE_WORDS = ["hey computer", "wake up"]
SLEEP_WORDS = ["computer go to sleep", "good night"]

# Speech to text
LANGUAGE = "en-us"

# Text generator
USER_NAME = "Marvin"
AI_NAME = "Computer"
LANGUAGE_MODEL_BASE_PATH = "./models/"
LANGUAGE_MODEL = "nous-hermes-13b.ggmlv3.q4_0.bin"
# LANGUAGE_MODEL = "ggml-mpt-7b-chat.bin"

# Text to speech
VOICE_ID = 'com.apple.eloquence.en-US.Reed'
